### ISSUE TITLE
перебор массива

### ISSUE THREAD

**Issue by ENoLTC** [frontenddevel0per/market-app-nextts#1]
https://github.com/frontenddevel0per/market-app-nextts/blob/d238025276cb32b86ca22fa358102f5cc2e2e84c/redux/bag/bag-slice.tsx#L15

здесь есть более подходящий метод - arr.includes()
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by ENoLTC** [comment]
мой косяк
используй find https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by frontenddevel0per** [comment]
`!state.value.some((e) => e.id === action.payload)`
Проверка нет ли в массиве объекта с id === action.payload
