### ISSUE TITLE
посмотреть позже

### ISSUE THREAD

**Issue by ENoLTC** [frontenddevel0per/market-app-nextts#14]
https://github.com/frontenddevel0per/market-app-nextts/blob/d238025276cb32b86ca22fa358102f5cc2e2e84c/components/sidebag/sidebag.component.tsx#L28

как-то странно это все. посмотрю позже, подумаю как сделать красивее

**Comment by frontenddevel0per** [comment]
<img width="459" alt="Вариант реализации" src="https://user-images.githubusercontent.com/65788920/189688285-380db91c-866b-4682-8723-4689177c51a9.png">
Как вариант, вроде выглядит неплохо
