### ISSUE TITLE
мэпинг данных

### ISSUE THREAD

**Issue by ENoLTC** [frontenddevel0per/market-app-nextts#15]
https://github.com/frontenddevel0per/market-app-nextts/blob/d238025276cb32b86ca22fa358102f5cc2e2e84c/components/item/item.component.tsx#L64

эти картинки можно мэпить. попозже напишу как сделать красивее

**Comment by frontenddevel0per** [comment]
<img width="347" alt="Более правильная реализация" src="https://user-images.githubusercontent.com/65788920/189684795-a304bf54-2204-4cea-b039-8a05dfe93de3.png">
