### ISSUE TITLE
ключ

### ISSUE THREAD

**Issue by ENoLTC** [frontenddevel0per/market-app-nextts#16]
https://github.com/frontenddevel0per/market-app-nextts/blob/d238025276cb32b86ca22fa358102f5cc2e2e84c/components/bag/bag.component.tsx#L8

не использовать index как ключ https://ru.reactjs.org/docs/lists-and-keys.html

**Comment by frontenddevel0per** [comment]
`BagItem key={item.id} id={item.id} count={item.count} />`
