### ISSUE TITLE
наполнение массива

### ISSUE THREAD

**Issue by ENoLTC** [frontenddevel0per/market-app-nextts#2]
https://github.com/frontenddevel0per/market-app-nextts/blob/d238025276cb32b86ca22fa358102f5cc2e2e84c/redux/bag/bag-slice.tsx#L17

не красивенько)
зачем ты так делаешь?
можно сделать куда проще

 `newArr = [...state.value, { id: action.payload, count: 1 }]`

**Comment by frontenddevel0per** [comment]
`state.value = [...state.value, { id: action.payload, count: 1 }]`
