### ISSUE TITLE
удаление элемента

### ISSUE THREAD

**Issue by ENoLTC** [frontenddevel0per/market-app-nextts#3]
https://github.com/frontenddevel0per/market-app-nextts/blob/d238025276cb32b86ca22fa358102f5cc2e2e84c/redux/bag/bag-slice.tsx#L33

а как в этом куске кода полностью удалить элемент из корзины? опиши плиз

**Comment by frontenddevel0per** [comment]
`if (item.id === action.payload && item.count > 1) {
          newArr.push({
            id: item.id,
            count: item.count - 1,
          });
        } else if (item.id !== action.payload) {
          newArr.push(item);
        }`
Тут схема довольно простая. Первое условие - это если вещь с нужным id имеет количество больше 1. Тогда просто возвращаю тот же объект, но со счётчиком на 1 меньше.
Второе условие это если вещь не с тем id, который нам нужен. Тогда мы просто её возвращаем.
И получается если счётчик нашего предмета равен одному, то он просто не возвращается, и засчёт 
того реализовано полное удаление предмета, проверил в local storage.
