### ISSUE TITLE
конфиг квериклиента

### ISSUE THREAD

**Issue by ENoLTC** [frontenddevel0per/market-app-nextts#5]
https://github.com/frontenddevel0per/market-app-nextts/blob/d238025276cb32b86ca22fa358102f5cc2e2e84c/pages/_app.tsx#L10

интереса ради попробуй наполнить его
как минимум я бы засунул туда св-о enabled: false

**Comment by frontenddevel0per** [comment]
`const queryClient = new QueryClient({
  defaultOptions: {
queries: {
      enabled: false,
      refetchOnWindowFocus: false,
      cacheTime: 60000,
    },
  },
});`
Автоматически не запускается, при фокусе обратно на браузер запросы не будут идти.
